### ISSUE TITLE
Compilation Failure in Windows with MinGW GCC

### ISSUE THREAD

**Issue by Social-Mean** [jkriege2/JKQtPlotter#124]
Dear developers,
I'm using GCC to compile  this project on Windows as follows:
1. Generate CMake config files (with my Qt path)
```
cmake .. -DCMAKE_PREFIX_PATH="C:\Qt\Qt5.12.12\5.12.12\mingw73_64\lib\cmake\Qt5\" -G "MinGW Makefiles"
```
And the output is
```
-- The CXX compiler identification is GNU 7.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CImg: trying to locate CImg library
CMake Warning (dev) in cmake/jkqtplotter_macros.cmake:
  A logical block opening on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:134 (function)

  closes on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:137 (endfunction)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/jkqtplotter_macros.cmake:
  A logical block opening on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:139 (function)

  closes on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:142 (endfunction)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/jkqtplotter_macros.cmake:
  A logical block opening on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:144 (function)

  closes on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:147 (endfunction)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in cmake/jkqtplotter_macros.cmake:
  A logical block opening on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:149 (function)

  closes on the line

    D:/dev/JKQtPlotter-master/cmake/jkqtplotter_macros.cmake:152 (endfunction)

  with mis-matching arguments.
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

--
-- =============================================================================
-- == JKQTPlotterLib Build Information                                        ==
-- =============================================================================
-- Version:               5.0.0
-- CMake Generator:       MinGW Makefiles
--    is multi-config:    NO
-- Build type:            Debug
-- Build types:
-- Build shared lib:      ON
-- Using CMake:           3.27.7
-- Using CMake Generator: MinGW Makefiles
-- Using compiler:        GNU 7.3.0, platform: MinGW
-- C++ Standard:          C++ 11, required: TRUE
-- LIB-Architecture:      CXX:  / BASE:
-- bit depth:             64 bit
-- System Name:           Windows
-- Processor Name:        AMD64
-- Using Qt:              5.12.12
--                        [at C:/Qt/Qt5.12.12/5.12.12/mingw73_64/lib/cmake/Qt5]
-- XITS fonts:            LINKED IN
-- FIRA fonts:            LINKED IN
-- Print support:         ON
-- Timing Info output:    ON
-- Precompiled Header:    ON
-- build JKQTMath:        ON
-- build JKQTMathText:    ON
-- build JKQTFastPlotter: ON
-- build JKQTPlotter:     ON
-- Installing to:         C:/Program Files (x86)/JKQTPlotter
-- =============================================================================
--
--
-- .............................................................................
-- .. BUILDING LIBRARIES
-- .............................................................................
-- -- Building JKQTCommon5
-- -- Building JKQTMath5
-- -- Building JKQTMathText5
-- -- Building JKQTFastPlotter5
CMake Warning at lib/jkqtfastplotter/CMakeLists.txt:7 (message):
  -- You are building the sub-library JKQTFastPlotter, which is DEPRECTAED
  and may be removed in future!


-- -- Building JKQTPlotter5
--
-- .............................................................................
-- .. BUILDING EXAMPLES
-- .............................................................................
-- ..   - CIMG NOT available: SKIPPING CImg-binding examples
-- ..   - OpenCV NOT available: SKIPPING OpenCV-binding examples
-- ..   - Precompiled Header:  ON
-- .............................................................................
-- .. BUILDING EXAMPLE TOOLS LIB:
-- -- Building JKQTPExampleToolsLib
-- .. BUILDING EXAMPLES FOR JKQTFASTPLOTTER:
-- ..   Building Example jkqtfastplotter_test
-- .. BUILDING EXAMPLES FOR JKQTMATHTEXT:
-- ..   Building Example jkqtmathtext_simpletest
-- ..   Building Example jkqtmathtext_test
-- .. BUILDING EXAMPLES FOR JKQTPLOTTER:
-- ..   Building Example simpletest
-- ..   Building Example jkqtplot_test
-- ..   Building Example advplotstyling
-- ..   Building Example barchart
-- ..   Building Example boxplot
-- ..   Building Example barchart_errorbars
-- ..   Building Example barchart_functorfill
-- ..   Building Example barchart_twocolor
-- ..   Building Example barchart_customdrawfunctor
-- ..   Building Example contourplot
-- ..   Building Example datastore
-- ..   Building Example datastore_groupedstat
-- ..   Building Example datastore_iterators
-- ..   Building Example datastore_regression
-- ..   Building Example datastore_statistics
-- ..   Building Example datastore_statistics_2d
-- ..   Building Example dateaxes
-- ..   Building Example distributionplot
-- ..   Building Example errorbarstyles
-- ..   Building Example evalcurve
-- ..   Building Example filledgraphs
-- ..   Building Example filledgraphs_errors
-- ..   Building Example functionplot
-- ..   Building Example geo_arrows
-- ..   Building Example geo_simple
-- ..   Building Example geo_coordinateaxis0
-- ..   Building Example geometric
-- ..   Building Example imageplot
-- ..   SKIPPING Example imageplot_cimg, CImg not found
-- ..   Building Example imageplot_modifier
-- ..   Building Example imageplot_nodatastore
-- ..   SKIPPING Example imageplot_opencv, OpenCV not found
-- ..   Building Example imageplot_userpal
-- ..   Building Example impulsesplot
-- ..   Building Example logaxes
-- ..   Building Example mandelbrot
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- ..   Building Example multiplot
-- ..   Building Example multithreaded
-- ..   Building Example parametriccurve
-- ..   Building Example paramscatterplot
-- ..   Building Example paramscatterplot_image
-- ..   Building Example paramscatterplot_customsymbol
-- ..   Building Example parsedfunctionplot
-- ..   Building Example rgbimageplot
-- ..   SKIPPING Example rgbimageplot_cimg, CImg not found
-- ..   SKIPPING Example rgbimageplot_opencv, OpenCV not found
-- ..   Building Example rgbimageplot_qt
-- ..   Building Example scatter
-- ..   Building Example scatter_customsymbol
-- ..   Building Example second_axis
-- ..   Building Example speed
-- ..   Building Example stackedbars
-- ..   Building Example stepplots
-- ..   Building Example styledboxplot
-- ..   Building Example styling
-- ..   Building Example symbols_and_errors
-- ..   Building Example symbols_and_styles
-- ..   Building Example ui
-- ..   Building Example user_interaction
-- ..   Building Example violinplot
-- ..   Building Example wiggleplots
--
-- .............................................................................
-- .. BUILDING TOOLS
-- .............................................................................
-- ..   - Precompiled Header:  ON
-- .............................................................................
-- .. BUILDING TOOLS FOR JKQTMATHTEXT:
-- ..   Building Tool jkqtmathtext_render
-- ..   Building Tool jkqtplotter_doc_imagegenerator
--
-- .............................................................................
-- .. BUILDING UNIT TESTS
-- .............................................................................
-- ..   - Precompiled Header:  ON
-- .............................................................................
-- .. BUILDING UNIT TESTS FOR JKQTCommon:
-- ..   Building Unit Test JKQTPStringTools_test
-- ..   Building Unit Test JKQTPCSSParser_test
-- ..   Building Unit Test JKQTPDataCache_test
-- ..   Building Unit Test JKQTPDataCache_benchmark
-- Configuring done (3.0s)
-- Generating done (6.5s)
-- Build files have been written to: D:/dev/JKQtPlotter-master/build
```
2. Build the project
```
cmake --build .
```
and the error occurs
```
[  0%] Automatic MOC and UIC for target JKQTCommon5
[  0%] Built target JKQTCommon5_autogen
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx.gch
In file included from D:/dev/JKQtPlotter-master/lib/jkqtcommon/private/jkqtcommon_precomp.h:80:0,
                 from D:/dev/JKQtPlotter-master/build/lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In function 'double jkqtp_j0(double)':
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:399:12: error: 'j0' was not declared in this scope
     return j0(x);
            ^~
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In function 'double jkqtp_j1(double)':
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:411:12: error: 'j1' was not declared in this scope
     return j1(x);
            ^~
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In function 'double jkqtp_y0(double)':
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:423:12: error: 'y0' was not declared in this scope
     return y0(x);
            ^~
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In function 'double jkqtp_y1(double)':
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:435:12: error: 'y1' was not declared in this scope
     return y1(x);
            ^~
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In function 'double jkqtp_jn(int, double)':
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:447:12: error: 'jn' was not declared in this scope
     return jn(n,x);
            ^~
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:447:12: note: suggested alternative: 'n'
     return jn(n,x);
            ^~
            n
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In function 'double jkqtp_yn(int, double)':
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:459:12: error: 'yn' was not declared in this scope
     return yn(n,x);
            ^~
D:/dev/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:459:12: note: suggested alternative: 'n'
     return yn(n,x);
            ^~
            n
mingw32-make.exe[2]: *** [lib\jkqtcommon\CMakeFiles\JKQTCommon5.dir\build.make:94: lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx.gch] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2505: lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/all] Error 2
mingw32-make.exe: *** [Makefile:145: all] Error 2
```
The error occurs in file `JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h`
https://github.com/jkriege2/JKQtPlotter/blob/ffb33a507e3d3237975c68ffd5df3c924b4b744b/lib/jkqtcommon/jkqtpmathtools.h#L394-L464
and `Q_CC_MSVC` is found in the scope. Maybe this error is related to GCC and windows.
Any suggestion is appreciated.

**Comment by jkriege2** [comment]
Hhmmm ... strange ... for me it works with MMnGW 7.3.0 ...

anyways, I just pushed a commit that includes the j0,j1, ... in another way (via a CMAKE check): https://github.com/jkriege2/JKQtPlotter/commit/b2b275f55434bfaf2958ae4b4afc8024b90c066d

Please check whether that works for you

**Comment by Social-Mean** [comment]
@jkriege2 Thank you for your reply and commit. The problem with `j0` and `j1` seems to have been solved. But following error occurs:
```
D:\dev\JKQtPlotter\build>cmake --build .
[  0%] Automatic MOC and UIC for target JKQTCommon5
[  0%] Built target JKQTCommon5_autogen
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpstringtools.cpp.obj
D:\dev\JKQtPlotter\lib\jkqtcommon\jkqtpstringtools.cpp: In lambda function:
D:\dev\JKQtPlotter\lib\jkqtcommon\jkqtpstringtools.cpp:396:44: error: 'NumPresets' is not a member of 'QGradient::Prese '
         for (int i=1; i<QGradient::Preset::NumPresets; i++) {
                                            ^~~~~~~~~~
mingw32-make.exe[2]: *** [lib\jkqtcommon\CMakeFiles\JKQTCommon5.dir\build.make:145: lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpstringtools.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2610: lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/all] Error 2
mingw32-make.exe: *** [Makefile:145: all] Error 2
```

**Comment by Social-Mean** [comment]
By the way, when I run `cmake .. -G "MinGW Makefiles"`, I got following error:
```
D:\dev\JKQtPlotter\build>cmake .. -G "MinGW Makefiles"
-- The CXX compiler identification is GNU 7.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at cmake/jkqtplotter_cmake_options.cmake:54 (warning):
  Unknown CMake command "warning".
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)


-- Configuring incomplete, errors occurred!
```
There have been errors like this before. That is not the problem with your commit.
I had to comment out line 54 of the file `cmake/jkqtplotter_cmake_options.cmake` to get it to work.

https://github.com/jkriege2/JKQtPlotter/blob/7f4972a0e1302397ec06594ea05f6c54b56dd856/cmake/jkqtplotter_cmake_options.cmake#L50-L58

This maybe a problem with CMake, my CMake doesn't recognize the `warning` command.

**Comment by Social-Mean** [comment]
New error!
```
D:\Downloads\JKQtPlotter-master(1)\JKQtPlotter-master\build>cmake --build . -j20
[  0%] Automatic MOC and UIC for target JKQTCommon5
[  0%] Built target JKQTCommon5_autogen
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx.gch
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/JKQTCommon5_autogen/mocs_compilation.cpp.obj
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpdebuggingtools.cpp.obj
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpmathtools.cpp.obj
[  0%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpstringtools.cpp.obj
[  1%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpcodestructuring.cpp.obj
[  1%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpbasicimagetools.cpp.obj
[  1%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpconcurrencytools.cpp.obj
[  1%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpcachingtools.cpp.obj
[  1%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpgeometrytools.cpp.obj
[  1%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpdrawingtools.cpp.obj
[  2%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpenhancedpainter.cpp.obj
[  2%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtphighrestimer.cpp.obj
[  2%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqttools.cpp.obj
In file included from D:\Downloads\JKQtPlotter-master(1)\JKQtPlotter-master\lib\jkqtcommon\jkqtpbasicimagetools.cpp:20: :
D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/jkqtpbasicimagetools.h:1206:50: error: 'QtPrivate::IfIsInputIterator' has not been declared
     template <typename InputIterator, QtPrivate::IfIsInputIterator<InputIterator> = true>
                                                  ^~~~~~~~~~~~~~~~~
D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/jkqtpbasicimagetools.h:1206:67: error: expected '>' before '<' token
     template <typename InputIterator, QtPrivate::IfIsInputIterator<InputIterator> = true>
                                                                   ^
[  2%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpicons.cpp.obj
[  2%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpcsstools.cpp.obj
[  2%] Building CXX object lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpexpected.cpp.obj
In file included from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/private/jkqtcommon_precomp.h:81:0,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/build/lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h: In instantiation of 'T jkqtp_reversed(const T&) [with T = QVector<unsigned int>]':
D:\Downloads\JKQtPlotter-master(1)\JKQtPlotter-master\lib\jkqtcommon\jkqtpbasicimagetools.cpp:116:100:   required from here
D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/jkqtpmathtools.h:667:12: error: no matching function for call to 'QVector<unsigned int>::QVector(QVector<unsigned int>::const_reverse_iterator, QVector<unsigned int>::const_reverse_iterator)'
     return T(l.rbegin(), l.rend());
            ^~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qdebug.h:51:0,
                 from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/QDebug:1,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/private/jkqtcommon_precomp.h:32,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/build/lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:516:1: note: candidate: QVector<T>::QVector(std::initializer_list<_Tp>) [with T = unsigned int]
 QVector<T>::QVector(std::initializer_list<T> args)
 ^~~~~~~~~~
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:516:1: note:   candidate expects 1 argument, 2 provided
In file included from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qdebug.h:51:0,
                 from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/QDebug:1,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/private/jkqtcommon_precomp.h:32,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/build/lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:76:5: note: candidate: QVector<T>::QVector(QVector<T>&&) [with T = unsigned int]
     QVector(QVector<T> &&other) Q_DECL_NOTHROW : d(other.d) { other.d = Data::sharedNull(); }
     ^~~~~~~
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:76:5: note:   candidate expects 1 argument, 2 provided
In file included from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qdebug.h:51:0,
                 from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/QDebug:1,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/private/jkqtcommon_precomp.h:32,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/build/lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:352:8: note: candidate: QVector<T>::QVector(const QVector<T>&) [with T = unsigned int]
 inline QVector<T>::QVector(const QVector<T> &v)
        ^~~~~~~~~~
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:352:8: note:   candidate expects 1 argument, 2 provided
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:494:1: note: candidate: QVector<T>::QVector(int, const T&) [with T = unsigned int]
 QVector<T>::QVector(int asize, const T &t)
 ^~~~~~~~~~
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:494:1: note:   no known conversion for argument 1 from 'QVector<unsigned int>::const_reverse_iterator {aka std::reverse_iterator<const unsigned int*>}' to 'int'
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:480:1: note: candidate: QVector<T>::QVector(int) [with T = unsigned int]
 QVector<T>::QVector(int asize)
 ^~~~~~~~~~
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:480:1: note:   candidate expects 1 argument, 2 provided
In file included from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qdebug.h:51:0,
                 from C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/QDebug:1,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/lib/jkqtcommon/private/jkqtcommon_precomp.h:32,
                 from D:/Downloads/JKQtPlotter-master(1)/JKQtPlotter-master/build/lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/cmake_pch.hxx:5,
                 from <command-line>:0:
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:69:12: note: candidate: QVector<T>::QVector() [with T = unsigned int]
     inline QVector() Q_DECL_NOTHROW : d(Data::sharedNull()) { }
            ^~~~~~~
C:/Qt/Qt5.12.12/5.12.12/mingw73_64/include/QtCore/qvector.h:69:12: note:   candidate expects 0 arguments, 2 provided
mingw32-make.exe[2]: *** [lib\jkqtcommon\CMakeFiles\JKQTCommon5.dir\build.make:179: lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/jkqtpbasicimagetools.cpp.obj] Error 1
mingw32-make.exe[2]: *** Waiting for unfinished jobs....
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:2610: lib/jkqtcommon/CMakeFiles/JKQTCommon5.dir/all] Error 2
mingw32-make.exe: *** [Makefile:145: all] Error 2
```

What is `QtPrivate::IfIsInputIterator`. I could not find any definition about it in this project or Qt.

**Comment by jkriege2** [comment]
hmmm ... it seems the code is more and more incompatible with older 5.xx Qt versions ... I usually test against the latest (and last, but also LTS) version (5.15) from the 5.xx branch ... could you switch to that version?

**Comment by jkriege2** [comment]
anyways ... I removed that use of QtPrivate, which seems to be missing in your Qt version ... could you try again?
