### ISSUE TITLE
Unable to build with Qt6.3

### ISSUE THREAD

**Issue by Neumann-A** [jkriege2/JKQtPlotter#71]
Error:
`E:\Repos\AllProjects\build\vcpkg_installed\x64-windows-llvm\include\Qt6\QtCore/qmetatype.h(872,49): error: member 'qt_check_for_QGADGET_macro' found in multiple base classes of different types
            IsRealGadget = sizeof(checkType(&T::qt_check_for_QGADGET_macro)) == sizeof(void *),`
real error:
```
E:\b\jkqtplotter\src\18a82dc8c7-5815fd25be.clean\lib\.\jkqtplotter/jkqtpgraphsbasestylingmixins.h(49,9): note: member found by ambiguous name lookup
        Q_GADGET
        ^
```
Full log:
[install-x64-windows-llvm-dbg-out.log](https://github.com/jkriege2/JKQtPlotter/files/8765577/install-x64-windows-llvm-dbg-out.log)

vcpkg overlay-ports for building jkqtplotter using vcpkg:
https://github.com/Neumann-A/my-vcpkg-ports/tree/master/jkqtplotter

**Comment by Neumann-A** [comment]
Seems like a compiler issue. Switching to MSVC instead of using LLVM fixed it.
