### ISSUE TITLE
Build error on mac jkqtfastplotter.cpp:342:28: Variable has incomplete type 'QPainterPath'

### ISSUE THREAD

**Issue by abdedixit** [jkriege2/JKQtPlotter#45]
Hi @jkriege2 ,

I am very eager to try this out, but I am facing the following build error while trying to build on macOS Catalina (v 10.15.5):

~/jkqtplotter/lib/jkqtmathtext/jkqtmathtext.cpp:40:18: error: 
      variable has incomplete type 'QPainterPath'
    QPainterPath path;
                 ^
In file included from ~/jkqtplotter/lib/jkqtmathtext/jkqtmathtext.cpp:22:
In file included from ~/jkqtplotter/lib/jkqtmathtext/jkqtmathtext.h:35:
In file included from /usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/QPainter:1:
In file included from /usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qpainter.h:48:
In file included from /usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qpixmap.h:49:
In file included from /usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qimage.h:48:
In file included from /usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qtransform.h:43:
/usr/local/Cellar/qt/5.15.0/lib/QtGui.framework/Headers/qmatrix.h:54:7: note: 
      forward declaration of 'QPainterPath'
class QPainterPath;

The workflow I followed:

1. Installed qt using homebrew:
% brew install qt5  

2. cmake .. -G "Xcode" "-DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.15.0" (This step worked fine)

3. cmake --build . --config "Debug" --> This step gave the above mentioned build error 

Please let me know if there is any fix/workaround for this. Also let me know if you need more info from my side.

**Comment by jkriege2** [comment]
Ahhh ... there seem to be some incompatibilities, introduced with Qt 5.15 (i.e. we need to #include <QPainterPath> now explicitly at some places) ... I'm working on a fix und will let you know when it's available

**Comment by jkriege2** [comment]
If you want to experiment by hand, add #include <QPainterPath> to these files:
jkqtmathtext.cpp
jkqtfastplotter.cpp

... and anywhere else, where the compiler complains!

**Comment by jkriege2** [comment]
OK, this issue should be fixed via https://github.com/jkriege2/JKQtPlotter/commit/7e9bad29b451acfebcdec78c25bc32164a0c1bfa

Could you confirm the fix?

**Comment by abdedixit** [comment]
Brilliant! This fix resolved the issue. Thanks!

The examples are really well made. I plan to use this tool in my audio signal processing research. Thanks again for the wonderful tool!

Best,
Abhi

**Comment by jkriege2** [comment]
You're welcome ... let me know if you have any more problems with the library!
